version: '3'

services:

  redis:
    container_name: live-video-streaming-redis
    build: ./redis
    ports:
      - '6377:6379'
    volumes:
      - ./redis/redis-data:/data
    environment:
      - REDIS_PASSWORD=default-password
    healthcheck:
      test: exit 0

  server:
    container_name: live-video-streaming-server
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - './server:/usr/src/app'
      - './server/package.json:/usr/src/package.json'
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_PASSWORD=default-password
      - TOKEN_SECRET=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe
      - TOKEN_SECRET_2=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe'\xab\xa6L6\xdd\x8d[\xccO\xfe
    depends_on:
      - redis
    links:
      - redis

  web-client:
    container_name: live-video-streaming-web-client
    build: ./client
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3333:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING=true
