version: '3'

services:

  redis:
    container_name: live-video-streaming-redis
    build: ./redis
    ports:
      - '6377:6379'
    volumes:
      - ./redis/redis-data:/data
    environment:
      - REDIS_PASSWORD=default-password
    healthcheck:
      test: exit 0

  db:
    container_name: live-video-streaming-db
    build: ./db
    volumes:
      - ./db/mongo-data:/data/db
    ports:
      - '27018:27017'
    healthcheck:
      test: exit 0

  server-signaling:
    container_name: live-video-streaming-server-signaling
    build: ./signaling
    ports:
      - '5002:3000'
    volumes:
      - './signaling:/usr/src/app'
      - './signaling/package.json:/usr/src/package.json'
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_PASSWORD=default-password
      - TOKEN_SECRET=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe
      - TOKEN_SECRET_2=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe'\xab\xa6L6\xdd\x8d[\xccO\xfe
    depends_on:
      - redis
    links:
      - redis

  server-api:
    container_name: live-video-streaming-server-api
    build: ./api
    ports:
      - '5001:3000'
    volumes:
      - './api:/usr/src/app'
      - './api/package.json:/usr/src/package.json'
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_PASSWORD=default-password
      - DATABASE_URL=mongodb://db:27017/dev
      - DATABASE_TEST_URL=mongodb://db:27017/test
      - TOKEN_SECRET=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe
      - TOKEN_SECRET_2=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe'\xab\xa6L6\xdd\x8d[\xccO\xfe
    depends_on:
      - redis
      - db
    links:
      - redis
      - db

  # web-client:
  #   container_name: live-video-streaming-web-client
  #   build: ./client
  #   volumes:
  #     - './client:/usr/src/app'
  #     - '/usr/src/app/node_modules'
  #   ports:
  #     - '3333:3000'
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - CHOKIDAR_USEPOLLING=true
